//! HTML format export for analytics reports.

use std::io::Write;

use crate::domain::analytics::AnalyticsReport;

/// Exports an analytics report to HTML format.
///
/// # Errors
///
/// Returns an [`io::Error`](std::io::Error) if writing fails.
pub fn export_report_to_html<W: Write>(
    report: &AnalyticsReport,
    writer: &mut W,
) -> std::io::Result<()> {
    // HTML header with embedded styles
    write_html_header(writer)?;

    // Title
    writeln!(writer, "<h1>📊 TaskFlow Analytics Report</h1>")?;
    writeln!(
        writer,
        "<p><strong>Period:</strong> {} to {}</p>",
        report.config.start_date, report.config.end_date
    )?;

    // Overview card
    write_overview_card(writer, report)?;

    // Status breakdown card
    write_status_card(writer, report)?;

    // Priority breakdown card
    write_priority_card(writer, report)?;

    // Velocity card
    write_velocity_card(writer, report)?;

    // Productivity insights card
    write_insights_card(writer, report)?;

    // Tag statistics card
    if !report.tag_stats.is_empty() {
        write_tags_card(writer, report)?;
    }

    // Project progress card
    if !report.burn_charts.is_empty() {
        write_projects_card(writer, report)?;
    }

    // Footer
    write_html_footer(writer)?;

    Ok(())
}

fn write_html_header<W: Write>(writer: &mut W) -> std::io::Result<()> {
    writeln!(writer, "<!DOCTYPE html>")?;
    writeln!(writer, "<html lang=\"en\">")?;
    writeln!(writer, "<head>")?;
    writeln!(writer, "  <meta charset=\"UTF-8\">")?;
    writeln!(
        writer,
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
    )?;
    writeln!(writer, "  <title>TaskFlow Analytics Report</title>")?;
    writeln!(writer, "  <style>")?;
    writeln!(
        writer,
        "    body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 900px; margin: 0 auto; padding: 20px; background: #f5f5f5; }}"
    )?;
    writeln!(
        writer,
        "    .card {{ background: white; border-radius: 8px; padding: 20px; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}"
    )?;
    writeln!(
        writer,
        "    h1 {{ color: #333; border-bottom: 2px solid #4CAF50; padding-bottom: 10px; }}"
    )?;
    writeln!(writer, "    h2 {{ color: #555; margin-top: 0; }}")?;
    writeln!(
        writer,
        "    table {{ width: 100%; border-collapse: collapse; margin: 10px 0; }}"
    )?;
    writeln!(
        writer,
        "    th, td {{ text-align: left; padding: 12px; border-bottom: 1px solid #ddd; }}"
    )?;
    writeln!(
        writer,
        "    th {{ background: #f8f8f8; font-weight: 600; }}"
    )?;
    writeln!(writer, "    tr:hover {{ background: #f5f5f5; }}")?;
    writeln!(
        writer,
        "    .metric {{ display: inline-block; background: #e8f5e9; padding: 8px 16px; border-radius: 20px; margin: 5px; }}"
    )?;
    writeln!(
        writer,
        "    .metric-value {{ font-weight: bold; color: #2e7d32; }}"
    )?;
    writeln!(
        writer,
        "    .trend-up {{ color: #4CAF50; }} .trend-down {{ color: #f44336; }} .trend-stable {{ color: #9e9e9e; }}"
    )?;
    writeln!(
        writer,
        "    .progress-bar {{ background: #e0e0e0; border-radius: 10px; overflow: hidden; height: 20px; }}"
    )?;
    writeln!(
        writer,
        "    .progress-fill {{ background: linear-gradient(90deg, #4CAF50, #8BC34A); height: 100%; transition: width 0.3s; }}"
    )?;
    writeln!(writer, "  </style>")?;
    writeln!(writer, "</head>")?;
    writeln!(writer, "<body>")?;
    Ok(())
}

fn write_html_footer<W: Write>(writer: &mut W) -> std::io::Result<()> {
    writeln!(
        writer,
        "<footer style=\"text-align: center; color: #888; margin-top: 40px;\">"
    )?;
    writeln!(writer, "  <p>Generated by TaskFlow</p>")?;
    writeln!(writer, "</footer>")?;
    writeln!(writer, "</body>")?;
    writeln!(writer, "</html>")?;
    Ok(())
}

fn write_overview_card<W: Write>(writer: &mut W, report: &AnalyticsReport) -> std::io::Result<()> {
    writeln!(writer, "<div class=\"card\">")?;
    writeln!(writer, "  <h2>Overview</h2>")?;
    writeln!(
        writer,
        "  <span class=\"metric\">Total Tasks: <span class=\"metric-value\">{}</span></span>",
        report.status_breakdown.total()
    )?;
    writeln!(
        writer,
        "  <span class=\"metric\">Completion Rate: <span class=\"metric-value\">{:.1}%</span></span>",
        report.status_breakdown.completion_rate() * 100.0
    )?;
    writeln!(
        writer,
        "  <span class=\"metric\">Completed: <span class=\"metric-value\">{}</span></span>",
        report.completion_trend.total_completed()
    )?;
    writeln!(
        writer,
        "  <span class=\"metric\">Created: <span class=\"metric-value\">{}</span></span>",
        report.completion_trend.total_created()
    )?;
    writeln!(writer, "</div>")?;
    Ok(())
}

fn write_status_card<W: Write>(writer: &mut W, report: &AnalyticsReport) -> std::io::Result<()> {
    writeln!(writer, "<div class=\"card\">")?;
    writeln!(writer, "  <h2>Status Breakdown</h2>")?;
    writeln!(writer, "  <table>")?;
    writeln!(writer, "    <tr><th>Status</th><th>Count</th></tr>")?;
    writeln!(
        writer,
        "    <tr><td>📋 To Do</td><td>{}</td></tr>",
        report.status_breakdown.todo
    )?;
    writeln!(
        writer,
        "    <tr><td>🔄 In Progress</td><td>{}</td></tr>",
        report.status_breakdown.in_progress
    )?;
    writeln!(
        writer,
        "    <tr><td>🚫 Blocked</td><td>{}</td></tr>",
        report.status_breakdown.blocked
    )?;
    writeln!(
        writer,
        "    <tr><td>✅ Done</td><td>{}</td></tr>",
        report.status_breakdown.done
    )?;
    writeln!(
        writer,
        "    <tr><td>❌ Cancelled</td><td>{}</td></tr>",
        report.status_breakdown.cancelled
    )?;
    writeln!(writer, "  </table>")?;
    writeln!(writer, "</div>")?;
    Ok(())
}

fn write_priority_card<W: Write>(writer: &mut W, report: &AnalyticsReport) -> std::io::Result<()> {
    writeln!(writer, "<div class=\"card\">")?;
    writeln!(writer, "  <h2>Priority Breakdown</h2>")?;
    writeln!(writer, "  <table>")?;
    writeln!(writer, "    <tr><th>Priority</th><th>Count</th></tr>")?;
    writeln!(
        writer,
        "    <tr><td>🔴 Urgent</td><td>{}</td></tr>",
        report.priority_breakdown.urgent
    )?;
    writeln!(
        writer,
        "    <tr><td>🟠 High</td><td>{}</td></tr>",
        report.priority_breakdown.high
    )?;
    writeln!(
        writer,
        "    <tr><td>🟡 Medium</td><td>{}</td></tr>",
        report.priority_breakdown.medium
    )?;
    writeln!(
        writer,
        "    <tr><td>🟢 Low</td><td>{}</td></tr>",
        report.priority_breakdown.low
    )?;
    writeln!(
        writer,
        "    <tr><td>⚪ None</td><td>{}</td></tr>",
        report.priority_breakdown.none
    )?;
    writeln!(writer, "  </table>")?;
    writeln!(writer, "</div>")?;
    Ok(())
}

fn write_velocity_card<W: Write>(writer: &mut W, report: &AnalyticsReport) -> std::io::Result<()> {
    writeln!(writer, "<div class=\"card\">")?;
    writeln!(writer, "  <h2>Velocity</h2>")?;
    writeln!(
        writer,
        "  <p><strong>Average Weekly:</strong> {:.1} tasks/week</p>",
        report.velocity.avg_weekly
    )?;
    let (trend_class, trend_icon) = if report.velocity.is_improving() {
        ("trend-up", "📈")
    } else if report.velocity.trend < 0.0 {
        ("trend-down", "📉")
    } else {
        ("trend-stable", "➡️")
    };
    writeln!(
        writer,
        "  <p><strong>Trend:</strong> <span class=\"{}\">{} {:+.1}</span></p>",
        trend_class, trend_icon, report.velocity.trend
    )?;
    if let Some((date, count)) = report.velocity.best_week() {
        writeln!(
            writer,
            "  <p><strong>Best Week:</strong> {} ({} tasks)</p>",
            date.format("%Y-%m-%d"),
            count
        )?;
    }
    writeln!(writer, "</div>")?;
    Ok(())
}

fn write_insights_card<W: Write>(writer: &mut W, report: &AnalyticsReport) -> std::io::Result<()> {
    writeln!(writer, "<div class=\"card\">")?;
    writeln!(writer, "  <h2>Productivity Insights</h2>")?;
    writeln!(
        writer,
        "  <p><strong>Current Streak:</strong> {} days{}</p>",
        report.insights.current_streak,
        if report.insights.is_best_streak() {
            " 🏆"
        } else {
            ""
        }
    )?;
    writeln!(
        writer,
        "  <p><strong>Longest Streak:</strong> {} days</p>",
        report.insights.longest_streak
    )?;
    if let Some(day) = report.insights.best_day {
        writeln!(
            writer,
            "  <p><strong>Most Productive Day:</strong> {day}</p>"
        )?;
    }
    if let Some(hour) = report.insights.peak_hour {
        writeln!(writer, "  <p><strong>Peak Hour:</strong> {hour}:00</p>")?;
    }
    if report.insights.total_time_tracked > 0 {
        let hours = report.insights.total_time_tracked / 60;
        let mins = report.insights.total_time_tracked % 60;
        writeln!(
            writer,
            "  <p><strong>Total Time Tracked:</strong> {hours}h {mins}m</p>"
        )?;
    }
    writeln!(writer, "</div>")?;
    Ok(())
}

fn write_tags_card<W: Write>(writer: &mut W, report: &AnalyticsReport) -> std::io::Result<()> {
    writeln!(writer, "<div class=\"card\">")?;
    writeln!(writer, "  <h2>Top Tags</h2>")?;
    writeln!(writer, "  <table>")?;
    writeln!(
        writer,
        "    <tr><th>Tag</th><th>Count</th><th>Completed</th><th>Rate</th></tr>"
    )?;
    for stat in report.tag_stats.iter().take(10) {
        writeln!(
            writer,
            "    <tr><td>#{}</td><td>{}</td><td>{}</td><td>{:.0}%</td></tr>",
            escape_html(&stat.tag),
            stat.count,
            stat.completed,
            stat.completion_rate() * 100.0
        )?;
    }
    writeln!(writer, "  </table>")?;
    writeln!(writer, "</div>")?;
    Ok(())
}

fn write_projects_card<W: Write>(writer: &mut W, report: &AnalyticsReport) -> std::io::Result<()> {
    writeln!(writer, "<div class=\"card\">")?;
    writeln!(writer, "  <h2>Project Progress</h2>")?;
    for chart in &report.burn_charts {
        let pct = chart.completion_percentage();
        writeln!(
            writer,
            "  <p><strong>{}</strong> - {:.0} remaining ({:.1}% complete)</p>",
            escape_html(&chart.project_name),
            chart.remaining_work(),
            pct
        )?;
        writeln!(writer, "  <div class=\"progress-bar\">")?;
        writeln!(
            writer,
            "    <div class=\"progress-fill\" style=\"width: {pct:.1}%\"></div>"
        )?;
        writeln!(writer, "  </div>")?;
    }
    writeln!(writer, "</div>")?;
    Ok(())
}

/// Escape special characters for HTML
pub(crate) fn escape_html(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#39;")
}

/// Exports an analytics report to a string in HTML format.
///
/// # Errors
///
/// Returns an [`io::Error`](std::io::Error) if formatting fails.
pub fn export_report_to_html_string(report: &AnalyticsReport) -> std::io::Result<String> {
    let mut buffer = Vec::new();
    export_report_to_html(report, &mut buffer)?;
    String::from_utf8(buffer).map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))
}
